// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	discover "github.com/quadroops/goplugin/pkg/discover"
	mock "github.com/stretchr/testify/mock"
)

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: content
func (_m *Parser) Parse(content []byte) (*discover.PluginConfig, error) {
	ret := _m.Called(content)

	var r0 *discover.PluginConfig
	if rf, ok := ret.Get(0).(func([]byte) *discover.PluginConfig); ok {
		r0 = rf(content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discover.PluginConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
