[meta]
version = "1.0.0"
author = "hiraq|hiraq.dev@gmail.com"
contributors = ['a|a@test.com','b|b@test.com']

# global configurations
[settings]
debug = true 

# Used as main plugin registries
#
# a plugin should provide basic five informations about their self
#
# - Author
# - Md5Sum.  To make sure that we should not be able to exec a plugin which will harm us
# - Exec path
# - Exec start time. Used to wait a plugin to start processes until they are ready to consume by caller
# - Communication type (grpc/rest)
#
# Each of registered plugin MUST have a unique's name
[plugins]

    [plugins.name_1]
    author = "author_1|author_1@gmail.com"
    md5 = "d194b7bad208c2ddfa0ef597fd4abcc5"
    exec = "/path/to/exec"
    exec_args = ["--port", "8080"]
    exec_file = "/path/to/exec"
    exec_time = 5
    comm_type = "grpc"
    comm_port = "8080"
    
    [plugins.name_2]
    author = "author_2|author_2@gmail.com"
    md5 = "d194b7bad208c2ddfa0ef597fd4abcc5"
    exec = "/path/to/exec"
    exec_args = ["--port", "8080"]
    exec_file = "/path/to/exec"
    exec_time = 10
    comm_type = "rest"
    comm_port = "8081"
    
    [plugins.name_3]
    author = "author_3|author_3@gmail.com"
    md5 = "d194b7bad208c2ddfa0ef597fd4abcc5"
    exec = "/path/to/exec"
    exec_args = ["--port", "8080"]
    exec_file = "/path/to/exec"
    exec_time = 20
    comm_type = "nano"
    comm_port = "8082"

# Used as service registries
# A service is an application that consume / using plugins
# They are not allowed to access a plugin that not registered to service's plugin registries
[hosts]

    [hosts.host_1]
    plugins = ["name_1", "name_2"]
    
    [hosts.host_2]
    plugins = ["name_3"]