// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	process "github.com/quadroops/goplugin/pkg/process"
	mock "github.com/stretchr/testify/mock"
)

// RegistryBuilder is an autogenerated mock type for the RegistryBuilder type
type RegistryBuilder struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *RegistryBuilder) Delete(_a0 string) {
	_m.Called(_a0)
}

// Get provides a mock function with given fields: _a0
func (_m *RegistryBuilder) Get(_a0 string) (process.Plugin, error) {
	ret := _m.Called(_a0)

	var r0 process.Plugin
	if rf, ok := ret.Get(0).(func(string) process.Plugin); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(process.Plugin)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsExist provides a mock function with given fields: _a0
func (_m *RegistryBuilder) IsExist(_a0 string) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *RegistryBuilder) Register(_a0 string, _a1 process.Plugin) {
	_m.Called(_a0, _a1)
}

// Reset provides a mock function with given fields:
func (_m *RegistryBuilder) Reset() {
	_m.Called()
}
