// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IdentityChecker is an autogenerated mock type for the IdentityChecker type
type IdentityChecker struct {
	mock.Mock
}

// Parse provides a mock function with given fields: source
func (_m *IdentityChecker) Parse(source string) (string, error) {
	ret := _m.Called(source)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(source)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(source)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
